name: MLOps Pipeline - Used Cars Price Prediction

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_ML_WORKSPACE: cars
  AZURE_RESOURCE_GROUP: default_resource_group
  AZURE_SUBSCRIPTION_ID: f2f9c878-1ca2-40dc-a868-b68e6b45074d

jobs:
  # Step 1: Data Preparation (mirrors Azure ML data prep job)
  data-preparation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn azure-ai-ml azure-identity
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run Data Preparation
      run: |
        echo "Running data preparation step..."
        python .github/workflows/run_pipeline.py --step data_prep
      env:
        AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
        AZURE_ML_WORKSPACE: ${{ env.AZURE_ML_WORKSPACE }}

  # Step 2: Model Training (mirrors Azure ML training job)  
  model-training:
    needs: data-preparation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity pandas scikit-learn mlflow
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run Model Training
      run: |
        echo "Running model training step..."
        python .github/workflows/run_pipeline.py --step training
      env:
        AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
        AZURE_ML_WORKSPACE: ${{ env.AZURE_ML_WORKSPACE }}

  # Step 3: Model Registration (mirrors Azure ML registration job)
  model-registration:
    needs: model-training
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity mlflow
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run Model Registration
      run: |
        echo "Running model registration step..."
        python .github/workflows/run_pipeline.py --step registration
      env:
        AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
        AZURE_ML_WORKSPACE: ${{ env.AZURE_ML_WORKSPACE }}
